# Generated by Django 4.2.7 on 2024-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="end_date",
            field=models.DateField(default="2024-04-30"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="start_date",
            field=models.DateField(default="2024-04-23"),
            preserve_default=False,
        ),
    ]
