# Generated by Django 4.2.7 on 2024-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_budget_end_date_budget_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
