# Generated by Django 4.2.7 on 2024-04-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_budget_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="is_active",
        ),
    ]
