# Generated by Django 4.2.7 on 2024-04-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_financetransaction_category"),
        ("category", "0003_customcategory"),
        ("goals", "0002_goal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.wallet",
            ),
            preserve_default=False,
        ),
    ]
