# Generated by Django 4.2.7 on 2024-05-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_goal_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="wallet",
        ),
    ]
