# Generated by Django 4.2.7 on 2024-04-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_category_icon"),
        ("finance", "0003_alter_financetransaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financetransaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.category"
            ),
        ),
    ]
