# Generated by Django 4.2.7 on 2024-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_financetransaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="NPR", max_length=10),
        ),
    ]
