# Generated by Django 4.2.7 on 2024-05-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_goal_user"),
        ("category", "0003_customcategory"),
        ("finance", "0005_wallet_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="financetransaction",
            name="custom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.customcategory",
            ),
        ),
        migrations.AddField(
            model_name="financetransaction",
            name="goals",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="goals.goal"
            ),
        ),
        migrations.AlterField(
            model_name="financetransaction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
    ]
