# Generated by Django 4.2.7 on 2024-05-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_financetransaction_custom_financetransaction_goals_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financetransaction",
            old_name="goals",
            new_name="goal",
        ),
    ]
