# Generated by Django 4.2.7 on 2024-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_icon",
            field=models.CharField(default="user", max_length=255),
            preserve_default=False,
        ),
    ]
