# Generated by Django 4.2.7 on 2024-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sujal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default="98", max_length=20),
            preserve_default=False,
        ),
    ]
