# Generated by Django 4.2.7 on 2024-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sujal", "0004_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
